# Generated by Django 4.1.2 on 2024-07-04 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.AutoField(db_column='id_categoria', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='myapp.categoria'),
        ),
    ]
